### ISSUE TITLE
Unable to run the application in browser

### ISSUE THREAD

**Issue by riteshsainju** [MacKentoch/react-director-admin-template#15]
I have installed all the required dependencies and when I tried to run the application in browser it gives me the error.
![errorreactapp](https://user-images.githubusercontent.com/19466365/45761138-5afe8980-bc4b-11e8-9814-e1aa57fcbc3b.PNG)

**Comment by MacKentoch** [comment]
Hi,

Could you share your dependencies versions please (*from your `package.json`*)?

**Comment by MacKentoch** [comment]
I mean effectively installed.

I suppose you have React 16.4+

**Comment by riteshsainju** [comment]
Thank you for the reply. Here is my package.json file. What changes do I need to make in order to run the application
[packagejsonfile.txt](https://github.com/MacKentoch/react-director-admin-template/files/2397596/packagejsonfile.txt)

**Comment by MacKentoch** [comment]
I'm sorry I was inaccurate, package.json does not tell effective installed dependencies.

Anyway, I'm pretty sure you have React 16..4+ (*since package.json tells to do so*), so:
- [comment in your code this line](https://github.com/MacKentoch/react-director-admin-template/blob/master/src/app/index.js#L8)
- [and comment this line too](https://github.com/MacKentoch/react-director-admin-template/blob/master/src/app/index.js#L27)

Then its should be ok

**Comment by riteshsainju** [comment]
Yes, it worked after I commented the lines as you suggested. Thank you.

**Comment by MacKentoch** [comment]
Alright, sorry for this issue.

I have to update this repo so that `react-tap-event-plugin` is no more used (*no more compatible with React 16.4+, since new lifecycle and context API I guess...*).

I close this issue, have a nice day!
